### ISSUE TITLE
what does this do and how do you use it

### ISSUE THREAD

**Issue by Pickymarker** [Duty-Core/t7_tool_ext#1]
what does this do and how do you use it

**Comment by approved** [comment]
Currently, it doesn't do much. 

This project is for the Black Ops 3 Mod Tools. It currently only offers the ability to change the splash screen for Radiant Black on the [cpp-0.1](https://github.com/Duty-Core/t7_tool_ext/tree/cpp-0.1) branch.

If you want to request a feature, make a new issue using the new request issue template.
